project:
  type: website
  output-dir: docs
  resources: images

website:
  title: "Operation Galiwatch"
  favicon: "images/teaswamp_transparent.png"
  page-footer:
    center: |
      *a Tea Swamp project* 
      <br>
      <a href="https://github.com/teaswamp-creations">
        <img src="https://raw.githubusercontent.com/teaswamp-creations/galiwatch.ca/quarto-website/images/teaswamp_transparent.png" alt="teaswamp logo: frog in mug" class="image" style="width: 5em;">
      </a>
  google-analytics: "G-YZBNVRR4EQ"
  navbar:
    right:
      - text: About
        href: about.qmd
      - text: Project Details
        href: project.qmd
      - text: Gallery
        href: gallery.qmd
      - text: Bee Book
        icon: box-arrow-up-right
        href: https://teaswamp-creations.github.io/bee-book
      - icon: github
        href: https://github.com/teaswamp-creations
  search: 
    location: navbar
    type: overlay
  
format:
  html:
    theme: 
      light: [yeti, css/light-theme.scss]
      dark: [yeti, css/dark-theme.scss]
    css: ["https://use.fontawesome.com/releases/v6.0.0/css/all.css"]



